In [1]:
import pandas as pd

train = pd.read_csv("DATASET1000_METPEN.csv")
test  = pd.read_csv("DATAUJI100_METPEN.csv")

print("=== INFO DATASET ===")
print("Jumlah data latih :", train.shape)
print("Jumlah data uji   :", test.shape)

print("\n DATA LATIH")
display(train.head(10))

=== INFO DATASET ===
Jumlah data latih : (1000, 3)
Jumlah data uji   : (100, 2)

 DATA LATIH

   id                                               teks    emosi
0   1                             bu sri mulyani diganti  negatif
1   2             Aku deg²kan Ketika Sri Mulyani diganti  negatif
2   3  BREAKING NEWS Isu Reshuffle Kabinet Kementrian...  negatif
3   4  Sri Mulyani diganti IHSG langsung merah Asik b...  negatif
4   5  Presiden Prabowo Reshuffle Kabinet Merah Putih...  negatif
5   6  Akhirnya Menkeu Sri Mulyani diganti Purbaya Yu...  negatif
6   7  Kemaren pada ribut minta Sri mulyani diganti S...  negatif
7   8                                Sri Mulyani diganti  negatif
8   9  Ternyata gerhana bulan blood moon memang berpe...  negatif
9  10                          sri mulyani diganti busri  negatif

In [2]:
print("\nDATA UJI")
display(test.head(10))

DATA UJI

    id                                               teks
0  522  Kebijakan impor dibahas kembali oleh Kementeri...
1  738  Budi buluk cengel apa dapet ingfoA1 dekat2 ini...
2  741  Pergantian Menteri Keuangan dianggap membawa r...
3  661  Respons akademisi terhadap pergantian Menteri ...
4  412   Reaksi demonstran terhadap Menteri Keuangan baru
5  679          Ternyata Bu Sri Mulyani bisa diganti juga
6  627  Presiden terpilih Prabowo Subianto diam diam s...
7  514          Sri Mulyani direshuffle diganti Sri Lanka
8  860  Sri Mulyani Mundur atau Dicopot Istana Buka Suara
9  137  Pergantian Menteri Keuangan dan reshuffle kabi...

In [3]:
label_map = {
    "negatif": 1,
    "positif": 0
}

train["label"] = train["emosi"].map(label_map)

print("=== CONTOH LABEL SETELAH MAPPING ===")
display(train[["teks","emosi","label"]].head(10))

=== CONTOH LABEL SETELAH MAPPING ===

                                                teks    emosi  label
0                             bu sri mulyani diganti  negatif      1
1             Aku deg²kan Ketika Sri Mulyani diganti  negatif      1
2  BREAKING NEWS Isu Reshuffle Kabinet Kementrian...  negatif      1
3  Sri Mulyani diganti IHSG langsung merah Asik b...  negatif      1
4  Presiden Prabowo Reshuffle Kabinet Merah Putih...  negatif      1
5  Akhirnya Menkeu Sri Mulyani diganti Purbaya Yu...  negatif      1
6  Kemaren pada ribut minta Sri mulyani diganti S...  negatif      1
7                                Sri Mulyani diganti  negatif      1
8  Ternyata gerhana bulan blood moon memang berpe...  negatif      1
9                          sri mulyani diganti busri  negatif      1

In [4]:
import re
import string

def clean_text(text):
    text = text.lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"@\w+", "", text)
    text = re.sub(r"#\w+", "", text)
    text = re.sub(r"[0-9]", "", text)
    text = text.translate(str.maketrans("", "", string.punctuation))
    return text.strip()

train["clean_text"] = train["teks"].astype(str).apply(clean_text)
test["clean_text"]  = test["teks"].astype(str).apply(clean_text)

print("=== CONTOH HASIL PREPROCESSING ===")
display(train[["teks","clean_text"]].head())

=== CONTOH HASIL PREPROCESSING ===

,teks,clean_text
0,bu sri mulyani diganti,bu sri mulyani diganti
1,Aku deg²kan Ketika Sri Mulyani diganti,aku deg²kan ketika sri mulyani diganti
2,BREAKING NEWS Isu Reshuffle Kabinet Kementrian...,breaking news isu reshuffle kabinet kementrian...
3,Sri Mulyani diganti IHSG langsung merah Asik b...,sri mulyani diganti ihsg langsung merah asik b...
4,Presiden Prabowo Reshuffle Kabinet Merah Putih...,presiden prabowo reshuffle kabinet merah putih...

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000)

X_train = vectorizer.fit_transform(train["clean_text"])
X_test  = vectorizer.transform(test["clean_text"])

y_train = train["label"]

print("=== UKURAN MATRIX TF-IDF ===")
print("X_train shape :", X_train.shape)
print("X_test shape  :", X_test.shape)

=== UKURAN MATRIX TF-IDF ===
X_train shape : (1000, 1825)
X_test shape  : (100, 1825)

In [6]:
from sklearn.neighbors import KNeighborsClassifier

knn_euclidean = KNeighborsClassifier(n_neighbors=7, metric='euclidean')
knn_euclidean.fit(X_train, y_train)

knn_euclid_pred = knn_euclidean.predict(X_test)

print("=== HASIL PREDIKSI KNN EUCLIDEAN (10 DATA PERTAMA) ===")
print(knn_euclid_pred)

=== HASIL PREDIKSI KNN EUCLIDEAN (10 DATA PERTAMA) ===
[1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1
 1 1 1 1 1 1 1 1 1 0 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1]

In [7]:
knn_manhattan = KNeighborsClassifier(n_neighbors=7, metric='manhattan')
knn_manhattan.fit(X_train, y_train)

knn_manhattan_pred = knn_manhattan.predict(X_test)

print("=== HASIL PREDIKSI KNN MANHATTAN (10 DATA PERTAMA) ===")
print(knn_manhattan_pred)

=== HASIL PREDIKSI KNN MANHATTAN (10 DATA PERTAMA) ===
[1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 0 1 1 0 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1]

In [9]:
hasil_knn_euclid = test.copy()
hasil_knn_euclid["prediksi_emosi"] = knn_euclid_pred

hasil_knn_manhattan = test.copy()
hasil_knn_manhattan["prediksi_emosi"] = knn_manhattan_pred

print("=== TABEL HASIL KNN EUCLIDEAN ===")
display(hasil_knn_euclid)

print("=== TABEL HASIL KNN MANHATTAN ===")
display(hasil_knn_manhattan)

=== TABEL HASIL KNN EUCLIDEAN ===

,id,teks,clean_text,prediksi_emosi
0,522,Kebijakan impor dibahas kembali oleh Kementeri...,kebijakan impor dibahas kembali oleh kementeri...,1
1,738,Budi buluk cengel apa dapet ingfoA1 dekat2 ini...,budi buluk cengel apa dapet ingfoa dekat ini k...,1
2,741,Pergantian Menteri Keuangan dianggap membawa r...,pergantian menteri keuangan dianggap membawa r...,1
3,661,Respons akademisi terhadap pergantian Menteri ...,respons akademisi terhadap pergantian menteri ...,1
4,412,Reaksi demonstran terhadap Menteri Keuangan baru,reaksi demonstran terhadap menteri keuangan baru,0
...,...,...,...,...
95,437,Respons santai publik terhadap Menteri Keuanga...,respons santai publik terhadap menteri keuanga...,1
96,765,Luar biasa untuk Indonesia Di video kali ini b...,luar biasa untuk indonesia di video kali ini b...,0
97,89,Salah satu alasan utama yang mendorong Sri Mul...,salah satu alasan utama yang mendorong sri mul...,1
98,64,JANGAN SAMPE IBU SRI MULYANI MUNDUR DARI JABAT...,jangan sampe ibu sri mulyani mundur dari jabat...,1
99,827,Kok berasa sedih yah Menteri Keuangan Bu Sri M...,kok berasa sedih yah menteri keuangan bu sri m...,1

=== TABEL HASIL KNN MANHATTAN ===

,id,teks,clean_text,prediksi_emosi
0,522,Kebijakan impor dibahas kembali oleh Kementeri...,kebijakan impor dibahas kembali oleh kementeri...,1
1,738,Budi buluk cengel apa dapet ingfoA1 dekat2 ini...,budi buluk cengel apa dapet ingfoa dekat ini k...,1
2,741,Pergantian Menteri Keuangan dianggap membawa r...,pergantian menteri keuangan dianggap membawa r...,1
3,661,Respons akademisi terhadap pergantian Menteri ...,respons akademisi terhadap pergantian menteri ...,1
4,412,Reaksi demonstran terhadap Menteri Keuangan baru,reaksi demonstran terhadap menteri keuangan baru,0
...,...,...,...,...
95,437,Respons santai publik terhadap Menteri Keuanga...,respons santai publik terhadap menteri keuanga...,0
96,765,Luar biasa untuk Indonesia Di video kali ini b...,luar biasa untuk indonesia di video kali ini b...,1
97,89,Salah satu alasan utama yang mendorong Sri Mul...,salah satu alasan utama yang mendorong sri mul...,1
98,64,JANGAN SAMPE IBU SRI MULYANI MUNDUR DARI JABAT...,jangan sampe ibu sri mulyani mundur dari jabat...,1
99,827,Kok berasa sedih yah Menteri Keuangan Bu Sri M...,kok berasa sedih yah menteri keuangan bu sri m...,1

In [ ]:
hasil_nb.to_csv("HASIL_NAIVE_BAYES.csv", index=False)
hasil_knn_euclid.to_csv("HASIL_KNN_EUCLIDEAN.csv", index=False)
hasil_knn_manhattan.to_csv("HASIL_KNN_MANHATTAN.csv", index=False)

print("=== FILE HASIL BERHASIL DISIMPAN ===")
print("HASIL_KNN_EUCLIDEAN.csv")
print("HASIL_KNN_MANHATTAN.csv")